name: Auto Absen

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.2
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run python script
      run: python main.py
    - name: Commit Changes
      run: |
        git config --local user.email "YOUR_EMAIL"
        git config --local user.name "YOUR_USERNAME"
        git add -A
        git commit -m "feat: add update to file log"
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: $\{{ secrets.GITHUB_TOKEN }}
        directory: "."
